config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :projects, except: :destroy do
    resources :comments, only: :create
  end

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :comment

  belongs_to :project
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  validates_presence_of :name, :description, :due_date

  has_many :project_statuses, -> { order 'created_at DESC' }
  has_many :comments, -> { order 'created_at DESC' }

  # Helper to get the current (most recent) project status
  def project_status
    project_statuses.first
  end

  # Helper to get the current (most recent) status
  def status
    project_status&.status
  end

  # Helper to get the ID of the current (most recent) status
  def status_id
    status&.id
  end
end

app/models/project_status.rb
class ProjectStatus < ApplicationRecord
  belongs_to :project
  belongs_to :status
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :project_statuses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :recoverable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project

  # POST /projects/:project_id/comments or /projects/:project_id/comments.json
  def create
    @comment = Comment.new(project: @project, user: current_user, comment: params[:comment][:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to project_url(@project), notice: "Comment was successfully added." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { redirect_to project_url(@project), alert: "Comment could not be added." }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_project
      @project = Project.find(params[:project_id])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update ]
  before_action :set_status, only: %i[ create update ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.project_statuses.new(status: @status)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    success = @project.transaction do
      @project.update(project_params)

      if @status != @project.status
        @project.project_statuses.create!(status: @status)
      end
    end

    respond_to do |format|
      if success
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # Assume people cannot delete projects
  # # DELETE /projects/1 or /projects/1.json
  # def destroy
  #   @project.destroy
  #
  #   respond_to do |format|
  #     format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def set_status
      @status = Status.find(params[:project][:status_id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :due_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Conversations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Project Conversations</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/projects">View all projects</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |type, message| %>
        <% bootstrap_class = (type == 'alert' ? 'danger' : 'success') %>

        <div class="alert alert-<%= bootstrap_class %> alert-dismissible fade show" role="alert">
          <%= message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="my-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="my-3">
    <%= form.label :due_date, class: "form-label" %>
    <%= form.text_field :due_date, class: "form-control", type: "date" %>
  </div>

  <div class="my-3">
    <%= form.label :status, class: "form-label" %>
    <%= form.collection_select(:status_id, Status.all, :id, :name, { prompt: true }, { class: "form-select" }) %>
  </div>

  <div class="my-3">
    <%= form.submit "Create Project", { class: "btn btn-primary" } %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= project.due_date %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<div class="my-3">
  <h1>Projects</h1>
</div>

<div class="my-3">
  <%= link_to(new_project_path) do %>
    <button type="button" class="btn btn-primary">
      <i class="bi bi-plus-circle"></i> New Project
    </button>
  <% end %>
</div>

<div id="projects">
  <% @projects.each do |project| %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= project.name %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= project.status&.name %></h6>
        <h6 class="card-subtitle mb-2 text-muted">Due <%= project.due_date&.strftime("%B %-d, %Y") %></h6>
        <p class="card-text"><%= project.description %></p>
        <%= link_to "View project", project %>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<div class="my-4">
  <h2><%= @project.name %></h2>
  <h3>Current Status: <%= @project.status&.name %></h3>
  <h4>Due Date: <%= @project.due_date&.strftime("%B %-d, %Y") %></h4>
  <p><%= @project.description %></p>
</div>

<div class="my-4">
  <%= form_for @project do |form| %>
    <div class="row">
      <span class="col">
        <%= form.collection_select(:status_id, Status.all, :id, :name, { prompt: true }, { class: "form-select" }) %>
      </span>
      <span class="col">
        <%= form.submit("Update Status", { class: "btn btn-primary" }) %>
      </span>
    </div>
  <% end %>
</div>

<div class="my-4">
  <h5>Status History</h5>
  <ul>
    <% @project.project_statuses.each do |project_status| %>
      <li>
        <%= project_status.created_at.strftime("%H:%M %B %-d, %Y") %> - <%= project_status.status.name %>
      </li>
    <% end %>
  </ul>
</div>

<div class="my-4">
  <h5>Project Conversation</h5>

  <% if @project.comments.empty? %>
    <p>No conversation yet...</p>
  <% else %>
    <% @project.comments.each do |comment| %>
      <div class="row">
        <div class="col-6 col-sm-3 col-md-2">
          <p>
            <b><%= comment.user.email %></b>
            <br />
            <i><%= comment.created_at.strftime("%H:%M:%S %B %-d, %Y") %></i>
          </p>
        </div>
        <div class="col-6 col-sm-9 col-md-10">
          <p><%= comment.comment %></p>
        </div>
      </div>
    <% end %>
  <% end %>

  <div>
    <%= form_for([@project, Comment.new]) do |form| %>
      <div class="row">
        <%= form.text_area(:comment, { class: "form-control my-1" }) %>
        <%= form.submit("Add Comment", { class: "btn btn-primary" }) %>
      </div>
    <% end %>
  </div>
</div>


<div>
  <%= link_to "Back to all projects", projects_path %>
</div>